services:
  db:
    image: postgres:17-alpine
    container_name: resto_db
    restart: always
    environment:
      POSTGRES_USER: resto_user
      POSTGRES_PASSWORD: juasjuas
      POSTGRES_DB: resto_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: resto_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@resto.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: